stage: prod
frontendHost: 'https://www.chessdojo.club'
mobileHost: 'exp://127.0.0.1:8081/--/'
discordFindGameChannelId: '972163822850814022'
discordPrivateGuildId: '951958534113886238'
discordPublicGuildId: '419042970558398469'
discordCoachingChannelId: '1197192211083833394'
discordAchievementsChannelId: '1296116461915345029'
discordFreeRoles: '1347231021359431832,1347232898700542022,1347233681521246289,1347233929891020851,1347234137781567518,1347234570679881769,1347234797902106717,1347234973698232404,1347235622636748892,1347236321915179050,1347236549292589186,1347237175481073746,1347236679034994800,1347237589429653545,1347237861795299379,1347238082146992198,1347238357155053611,1347238748538142793,1347238961252274197,1347239103904878715,1347239296448336033,1347239445308506215,1347240083052560415'
discordPaidRoles: '1107651005547548742,951960545077100645,951995036487254026,1107650883807891547,951995253378940999,1007088844425932820,951995299407212564,1007089559550570578,951995406835925042,951995460174872586,951995519272624179,951996640271675403,951995556287377438,951995620049190942,951995656959058010,951995701909409862,951995756057882665,951995789935247441,951995832327086090,951995870264569916,951995912564121601,951995973385740329,951996035792764998'
discordOpenClassicalRole: '1366468011489230858'
monthlySubscriptionPriceId: 'price_1QfochGilmvijaecMoRiqYX4'
yearlySubscriptionPriceId: 'price_1QfobuGilmvijaecbgMcwHz0'
quickGameReviewPriceId: 'price_1Ou1BnGilmvijaecDU2PD2tx'
deepGameReviewPriceId: 'price_1Ou1BeGilmvijaecRni6KRJU'
hostedZoneId: 'Z03344272RB3HOTGLLT2U'
cognitoUserPoolDomain: 'auth.chessdojo.club'
coaches: 'google_108763076343237273295,google_100898429805622416873,google_111679691028507818183,google_114391023466287136398,8acfb26f-641f-4508-a15b-581d6b9b6230,google_113707626898571235301,6f4d7501-f2d1-48b3-89f6-de48c19975d6'
