stage: dev
frontendHost: 'http://localhost:3000'
mobileHost: 'exp://127.0.0.1:8081/--/'
discordFindGameChannelId: '1078714829709262858'
discordPrivateGuildId: '691123894001598536'
discordPublicGuildId: '1154831716100341810'
discordCoachingChannelId: '1210626160527147038'
monthlySubscriptionPriceId: 'price_1OHv1sGilmvijaecXqH8xxFi'
yearlySubscriptionPriceId: 'price_1OHv1sGilmvijaecuCh0DliE'
quickGameReviewPriceId: 'price_1OsvY7GilmvijaecdrvA9Vx1'
deepGameReviewPriceId: 'price_1OsvZ9GilmvijaeciXPyIdTa'
domainCertificateArn: 'arn:aws:acm:us-east-1:717403174598:certificate/15fcadca-b240-416d-a905-08572cddd572'
coaches: 'google_112538452360881134254'
