stage: dev
frontendHost: 'http://localhost:3000'
mobileHost: 'exp://127.0.0.1:8081/--/'
discordFindGameChannelId: '1078714829709262858'
discordPrivateGuildId: '691123894001598536'
discordPublicGuildId: '1154831716100341810'
discordCoachingChannelId: '1210626160527147038'
discordAchievementsChannelId: '1245135035741245572'
monthlySubscriptionPriceId: 'price_1OHv1sGilmvijaecXqH8xxFi'
yearlySubscriptionPriceId: 'price_1QdHonGilmvijaecqvN7D0jd'
quickGameReviewPriceId: 'price_1OsvY7GilmvijaecdrvA9Vx1'
deepGameReviewPriceId: 'price_1OtFn8GilmvijaeciBHaXveO'
roundRobinPriceId: 'price_1QencyGilmvijaecHUZufLfd'
hostedZoneId: 'Z03344272RB3HOTGLLT2U'
cognitoUserPoolDomain: 'authdev.chessdojo.club'
coaches: 'google_112538452360881134254'
