stage: prod
frontendHost: 'https://www.dojoscoreboard.com'
mobileHost: 'exp://127.0.0.1:8081/--/'
discordFindGameChannelId: '972163822850814022'
discordPrivateGuildId: '951958534113886238'
discordPublicGuildId: '419042970558398469'
discordCoachingChannelId: '1197192211083833394'
monthlySubscriptionPriceId: 'price_1OJIsJGilmvijaecExwiQfAX'
yearlySubscriptionPriceId: 'price_1OJIsJGilmvijaec2sL831rf'
quickGameReviewPriceId: 'price_1Ou1BnGilmvijaecDU2PD2tx'
deepGameReviewPriceId: 'price_1Ou1BeGilmvijaecRni6KRJU'
domainCertificateArn: 'arn:aws:acm:us-east-1:717403174598:certificate/15fcadca-b240-416d-a905-08572cddd572'
coaches: 'google_108763076343237273295,google_100898429805622416873,google_111679691028507818183,google_114391023466287136398,8acfb26f-641f-4508-a15b-581d6b9b6230,google_113707626898571235301'
