# Deploys the chat bot service.

service: chess-dojo-chat-bot

plugins:
  - serverless-plugin-custom-roles
  - serverless-esbuild

package:
  individually: true

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  logRetentionInDays: 14
  environment:
    stage: ${sls:stage}
    endpoint: ${file(../ai.yml):endpoint}
    agent: ${file(../ai.yml):agent}
  httpApi:
    id: ${param:httpApiId}
  deploymentMethod: direct

functions:
  chat:
    handler: chat.handler
    timeout: 25
    events:
      - httpApi:
          path: /public/dojoai/chat
          method: post

  history:
    handler: chatHistory.handler
    events:
      - httpApi:
          path: /public/dojoai/chat
          method: get
